#ifndef PDFNetOBJC_Private_H
#define PDFNetOBJC_Private_H

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#import <Foundation/Foundation.h>


@interface SWIGTYPE_p_unsigned_char : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_Obj : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_TextExtractorStyle : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_p_unsigned_int : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_p_void : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_HTML2PDF_Proxy : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_PDFDoc : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_TextExtractorWord : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_p_pdftron__PDF__PDFView__HTTPRequestOptions : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_Redaction : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_SecurityHandler : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_HTML2PDF_TOCSettings : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_HTML2PDF_WebPageSettings : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_TRN_TextExtractorLine : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_Int64 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_PrinterMode__PaperSize : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (id)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end



#endif // PDFNetOBJC_Private_H

